version: "3.8"
services:
  flask: #  <name of dir>_flask
    build:
      context: .
    image: 'docker101'
    command: "python app.py"
    ports:
    - 5000:5000
    volumes:
      - ./:/app

#    environment:
#      - PORT=9000
#      - HOST=10.0.0.1
#    env_file:
#      - .env
